#@ load("/values.star", "values")
#@ load("@ytt:overlay", "overlay")
#@ load("/ociconf.lib.txt", "oci_conf")

#@overlay/match by=overlay.subset({"kind": "Secret", "metadata": {"name": "oci-cloud-controller-manager"}})
---
#@overlay/replace
stringData:
  cloud-provider.yaml: #@ oci_conf(values)
