apiVersion: v1
kind: Secret
metadata:
  name: oci-cloud-controller-manager
  namespace: kube-system
stringData:
  cloud-provider.yaml: |-
    useInstancePrincipals: true
    
    # compartment configures Compartment within which the cluster resides.
    compartment: ${OCI_COMPARTMENT_ID}
    
    loadBalancer:
      disabled: true
    # Optional rate limit controls for accessing OCI API
    rateLimiter:
      rateLimitQPSRead: 20.0
      rateLimitBucketRead: 5
      rateLimitQPSWrite: 20.0
      rateLimitBucketWrite: 5